# -*- coding: utf-8 -*-
"""EduTutor project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AoOEKnG5Y_XcZjgpWK6VPLC6M6DC-Y_B
"""

!pip install gradio PyPDF2 transformers torch bitsandbytes -q

import gradio as gr
import torch
import PyPDF2
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline

# Load model
try:
    model_name = "ibm-granite/granite-3.3-2b-instruct"
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForCausalLM.from_pretrained(model_name, device_map="auto", load_in_8bit=True)
    generator = pipeline("text-generation", model=model, tokenizer=tokenizer, max_new_tokens=512)
    print("✅ Model loaded.")
except Exception as e:
    print(f"❌ Model loading failed: {e}")
    generator = None

def generate_response(prompt):
    if generator is None:
        return "❌ Model not loaded"
    try:
        out = generator(prompt)
        return out[0]["generated_text"]
    except Exception as e:
        return f"❌ Generation error: {e}"

def concept_understanding(concept):
    prompt = f"Explain '{concept}' simply for a 15-year-old with real examples."
    return generate_response(prompt)

def generate_test_from_pdf(pdf_file):
    try:
        reader = PyPDF2.PdfReader(pdf_file)
        text = " ".join([page.extract_text() for page in reader.pages if page.extract_text()])
        if not text:
            return "❌ No text found in PDF."
        prompt = f"""
Make MCQs from this content:

{text}

Format:
Qn: <question>
A. <option A>
B. <option B>
C. <option C>
D. <option D>
Correct Answer: <letter>
"""
        return generate_response(prompt)
    except Exception as e:
        return f"❌ PDF error: {e}"

demo = gr.Interface(
    fn=lambda concept, pdf: (concept_understanding(concept), generate_test_from_pdf(pdf)),
    inputs=[
        gr.Textbox(label="Enter Concept"),
        gr.File(label="Upload PDF")
    ],
    outputs=[
        gr.Textbox(label="Concept Explanation"),
        gr.Textbox(label="Test from PDF")
    ],
    title="EduTutor AI – Personalized Learning with IBM Granite"
)

demo.launch(share=True)

